services:
  jupyter-lab:
    image: hjben/jupyter-lab:latest
    hostname: jupyter-lab
    container_name: jupyter-lab
    privileged: true
    ports:
      - 8888:8888
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/a10053/workspace/docker-ws/kafka-notebook:/root/workspace
    networks:
      kafka-cluster:
        ipv4_address: 10.0.2.2
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "cmak:10.0.2.3"
      - "kafka1:10.0.2.4"
      - "kafka2:10.0.2.5"
      - "kafka3:10.0.2.6"

  cmak:
    image: hjben/cmak:3.0.0.5
    hostname: cmak
    container_name: cmak
    privileged: true
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: 10.0.3.1:2181,10.0.3.1:2182,10.0.3.1:2183
      APPLICATION_SECRET: "random-secret"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      kafka-cluster:
        ipv4_address: 10.0.2.3
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "cmak:10.0.2.3"
      - "kafka1:10.0.2.4"
      - "kafka2:10.0.2.5"
      - "kafka3:10.0.2.6"

  kafka1:
    image: hjben/kafka:2.7.0
    hostname: kafka1
    container_name: kafka1
    privileged: true
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://127.0.0.1:9093
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ZOOKEEPER_CONNECT: 10.0.3.1:2181,10.0.3.1:2182,10.0.3.1:2183/kafka
      JMX_PORT: 9999
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/kafka/logs/kafka1:/usr/local/kafka/logs
      - /tmp/kafka/data:/kafka
    networks:
      kafka-cluster:
        ipv4_address: 10.0.2.4
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "cmak:10.0.2.3"
      - "kafka1:10.0.2.4"
      - "kafka2:10.0.2.5"
      - "kafka3:10.0.2.6"
  kafka2:
    image: hjben/kafka:2.7.0
    hostname: kafka2
    container_name: kafka2
    privileged: true
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://127.0.0.1:9094
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ZOOKEEPER_CONNECT: 10.0.3.1:2181,10.0.3.1:2182,10.0.3.1:2183/kafka
      JMX_PORT: 9999
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/kafka/logs/kafka2:/usr/local/kafka/logs
      - /tmp/kafka/data:/kafka
    networks:
      kafka-cluster:
        ipv4_address: 10.0.2.5
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "cmak:10.0.2.3"
      - "kafka1:10.0.2.4"
      - "kafka2:10.0.2.5"
      - "kafka3:10.0.2.6"
  kafka3:
    image: hjben/kafka:2.7.0
    hostname: kafka3
    container_name: kafka3
    privileged: true
    ports:
      - 9095:9095
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://127.0.0.1:9095
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9095
      KAFKA_ZOOKEEPER_CONNECT: 10.0.3.1:2181,10.0.3.1:2182,10.0.3.1:2183/kafka
      JMX_PORT: 9999
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/kafka/logs/kafka3:/usr/local/kafka/logs
      - /tmp/kafka/data:/kafka
    networks:
      kafka-cluster:
        ipv4_address: 10.0.2.6
    extra_hosts:
      - "jupyter-lab:10.0.2.2"
      - "cmak:10.0.2.3"
      - "kafka1:10.0.2.4"
      - "kafka2:10.0.2.5"
      - "kafka3:10.0.2.6"

networks:
 kafka-cluster:
  ipam:
   driver: default
   config:
   - subnet: 10.0.2.0/24
     gateway: 10.0.2.1
